# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 054d15d25dbcc7ecc95efc0a04e99308740a712e0db6ca4ebe187e70e6286cd89c13765787f8202ef351dcbced5c74697cfb17ccfb60e0cabdc814b47977b39c

test:
  secret_key_base: f58abf4c3d2d75c31cd07f52be35a436d30d4277eacc37be83a17ddf60e95d9b4bc6a9756b1d2718b194d0957043d81fe31a3f6d8c03b84c29e059d427bbcaa1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
